### PR TITLE
all resources: Grant object owners to connected user when needed.

### LINKED ISSUE #36: Can not destroy postgresql_role after create
Hi there,

I have a problem with destroying postgres role with database, created before.

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.17.0
+ provider.postgresql v0.1.1
+ provider.template v1.0.0
```

### Affected Resource(s)
- postgresql_role

### Terraform Configuration Files
```hcl
provider "postgresql" {
  alias    = "rds"
  host     = "${var.rds_endpoint}"
  username = "${var.rds_master_username}"
  password = "${var.rds_master_password}"
}

resource "postgresql_role" "tenant" {
  provider        = "postgresql.rds"
  name            = "${local.tenant_name}"
  login           = true
  password        = "${local.tenant_name}"
  create_database = true
}
```

### Debug Output
```
2018/05/09 10:32:39 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* postgresql_role.tenant (destroy): 1 error(s) occurred:

* postgresql_role.tenant: Error deleting role: pq: permission denied to reassign objects

```

### Expected Behavior
Role deleted, database deleted

### Actual Behavior
Role and database still existing.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform destroy`

### References
Same error noticed here but no answer
- https://github.com/hashicorp/terraform/pull/11452

### PR DESCRIPTION
**Pull request by cyrilgdn**
This should fix most of permissions problems the provider has when running against RDS databases (and maybe other Cloud provider, but didn't test yet)

This also adds a new run of integration tests against a RDS-like Postgres.

Some tests are disabled for this environment, either because it really need to be superuser (e.g. to create a new superuser) or because the environment is not totally similar as RDS (e.g.: for the extensions, I need to check how I can reproduce RDS behavior).

This replaces #139 and #135 
Thanks to @slocke716 and @rimmington for your work on these problems that help me to create a more generic fix. If you have time to test this PR on your environment to assert it fixes your use cases, and even more to make a review of this PR, it would be very helpful :blush: .

This (hopefully) fixes #36

### CODE REVIEW

File: postgresql/resource_postgresql_schema.go [hunk 1]
```diff
@@ -121,25 +122,57 @@ func resourcePostgreSQLSchema() *schema.Resource {
...
 	txn, err := startTransaction(c, database)
 	if err != nil {
 		return err
 	}
 	defer deferredRollback(txn)
 
+	// If the admin user is not a superuser (e.g. on AWS RDS)
+	// we'll need to temporary grant him:
+	//  * the owner of the db to have the permissions to create the schema
+	//  * the owner of the schema if specified in order to change its owner.
```
Comment (mltsy) [inline postgresql/resource_postgresql_schema.go:138]:
```suggestion
	// If the current_user is not a superuser (e.g. on AWS RDS)
	// we'll need to temporary grant it membership in the following roles:
	//  * the owner of the db (to have the permissions to create the schema)
	//  * the owner of the schema, if it has one (in order to change its owner)
```

**Comment by slocke716** [comment]
> This should fix most of permissions problems the provider has when running against RDS databases (and maybe other Cloud provider, but didn't test yet)
> 
> This also adds a new run of integration tests against a RDS-like Postgres.
> 
> Some tests are disabled for this environment, either because it really need to be superuser (e.g. to create a new superuser) or because the environment is not totally similar as RDS (e.g.: for the extensions, I need to check how I can reproduce RDS behavior).
> 
> This replaces #139 and #135
> Thanks to @slocke716 and @rimmington for your work on these problems that help me to create a more generic fix. If you have time to test this PR on your environment to assert it fixes your use cases, and even more to make a review of this PR, it would be very helpful  .
> 
> This (hopefully) fixes #36

Sorry for the dreadfully late reply. Do you still need testing against an rds instance? If so, is it sufficient to just spin up a "free-tier" and point the tests to this or are you looking for something more detailed?

**Comment by cyrilgdn** [comment]
> Sorry for the dreadfully late reply. Do you still need testing against an rds instance? If so, is it sufficient to just spin up a "free-tier" and point the tests to this or are you looking for something more detailed?

@slocke716 It was more if you can easily test and assert it fixes the specific use case you created your PR for.

We're using this patched version against RDS so I know it works but maybe you have a specific use case that we are not covering neither does the acceptance tests.

File: postgresql/resource_postgresql_schema.go [hunk 2]
```diff
@@ -121,25 +122,57 @@ func resourcePostgreSQLSchema() *schema.Resource {
...
+func createSchema(d *schema.ResourceData, c *Client, txn *sql.Tx) error {
 	schemaName := d.Get(schemaNameAttr).(string)
 
 	// Check if previous tasks haven't already create schema
 	var foundSchema bool
-	err = txn.QueryRow(`SELECT TRUE FROM pg_catalog.pg_namespace WHERE nspname = $1`, schemaName).Scan(&foundSchema)
+	err := txn.QueryRow(`SELECT TRUE FROM pg_catalog.pg_namespace WHERE nspname = $1`, schemaName).Scan(&foundSchema)
 
+	queries := []string{}
 	if err == sql.ErrNoRows {
```
Comment (paultyng) [inline postgresql/resource_postgresql_schema.go:176]: I feel like this may leak other errors here, you don't do anything in the case that its an error but not no rows (ie network problem, etc).

Comment (cyrilgdn) [reply postgresql/resource_postgresql_schema.go]: Indeed, I've just added a commit to handle correctly this error with a test to assert it works as expected.

**Comment by cyrilgdn** [comment]
FYI, this has just been released in  [v1.7.0](https://github.com/terraform-providers/terraform-provider-postgresql/blob/master/CHANGELOG.md#170-july-17-2020).

**Comment by mltsy** [comment]
It works!  Thank you so much for this amazing birthday gift! 🙏
