### PR TITLE
Travis: Build agains multiple Postgres version + fix bugs

### LINKED ISSUE #35: Update of CONNECTION LIMIT for database fails
### Terraform Version
```
Terraform v0.11.7
```

### Affected Resource(s)
- postgresql_database

### Terraform Configuration Files
```hcl
resource "postgresql_database" "mylittledatabase" {
  name              = "mylittledatabase"
  owner             = "mylittledatabase_dba"
  connection_limit  = 100 
  allow_connections = true
}
```

### Expected Behavior
New CONNECTION LIMIT for a database is set.

### Actual Behavior
An error is thrown:
```
Error updating database CONNECTION LIMIT: pq: syntax error at or near "$1"
```

### Steps to Reproduce
1. Create a database with a set connection limit.
2. `terraform apply`
3. Change the connection limit
4. `terraform apply` again

-> BOOM ;-)

### Workaround:

It seems this is an issue with the call of db.Exec (https://github.com/terraform-providers/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_database.go#L487). I did check that connLimit contains an int of the desired value, so that's NOT the issue there. And if I change the code to apply the connLimit variable in the SQL statement like so:

```
dbName := d.Get(dbNameAttr).(string)
sql := fmt.Sprintf("ALTER DATABASE %s CONNECTION LIMIT %d", pq.QuoteIdentifier(dbName), connLimit)

if _, err := db.Exec(sql); err != nil {
  return errwrap.Wrapf("Error updating database CONNECTION LIMIT: {{err}}", err)
}
```

it works fine.

### PR DESCRIPTION
**Pull request by cyrilgdn**
Acceptance tests was not run in Travis so I configured Travis to start Postgres server in a Docker container (with a Matrix of versions from 8.4 to latest) and enable acceptance tests against it.

By running these tests, I discovered multiple bugs that I fixed:

* The version features flags system was not working because the detected version was not correctly set in the Client struct...
* Database update was not working because of invalid SQL queries (using of statement parameters syntax "$1" but not for parameters...)
* Disable postgresql_extension resource (and associated tests) for Postgres < 9.1 (`CREATE EXTENSION` does not exists before this version)
* Add a replication flag (available for >=9.1)

fix #35

### CODE REVIEW

File: tests/env.sh [hunk 1]
```diff
@@ -0,0 +1,6 @@
+export TF_ACC=true
```
Comment (paultyng) [inline tests/env.sh]: You shouldn't need this here if you are running `make testacc`

Comment (cyrilgdn) [reply tests/env.sh]: @paultyng Indeed, but when I run some tests manually during development I use to `source tests/env.sh` then I'm able to run `go test ...` to target specific tests.

Comment (paultyng) [reply tests/env.sh]: I typically just do:

```shell
TESTARGS="-cover -run 'MyTest'" make testacc
```

But feel free to merge if you prefer your style.
